site_name: Prime Ball Controller
theme: readthedocs
markdown_extensions:
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - attr_list
  - admonition
  - abbr
  - pymdownx.mark
  - pymdownx.magiclink

nav:
- 'Welcome': index.md
- 'Playable Demos': demo/demo.md
- 'Download from Unity Asset Store': https://assetstore.unity.com/packages/tools/physics/prime-ball-controller-229154/
- 'Help and Support': support.md
- 'Roadmap': roadmap.md
- 'Release History ': release-history.md
- 'Getting Started':
  - 'Installation / Setup': installation/installation-overview.md
  - 'Basic Setup': installation/basic-installation.md
  - 'Detailed Setup': installation/detailed-installation.md
  - 'Setup With Existing Cinemachine': installation/installation-previous-cinemachine.md
  - 'Using Different Render Pipelines': installation/builtin-urp-hdrp.md
  - 'Mobile Controls': mobile/control.md
- 'Demo Scenes':
  - 'Scenes': scenes/scenes.md
- 'Controller Options': 
  - 'Overview': controller_options/overview.md
  - 'Input Mapping': controller_options/input-mapping.md
  - 'Cameras': controller_options/cinemachine.md
  - 'Free Look Camera': controller_options/standard-camera-settings.md
  - 'Projectile Camera': controller_options/projectilecamera.md
  - 'Fps Camera': controller_options/fpscamera.md
  - 'Sphere': controller_options/sphere-player.md
  - 'Mesh': controller_options/mesh-rotation.md
  - 'Movement': controller_options/sphere-movement.md
  - 'Gravity': controller_options/gravity.md
  - 'Jump': controller_options/jump.md
  - 'Boost': controller_options/boost.md
  - 'Boost Jump': controller_options/boostjump.md
  - 'Sprint': controller_options/sprint.md
  - 'Magnet': controller_options/magnet.md
  - 'Grapple Swing': controller_options/grappleswing.md
  - 'Grapple Hook': controller_options/grapplehook.md
  - 'Projectile': controller_options/projectile.md
- 'Zones': 
  - 'Overview': camera_zones/overview.md
  - 'Creating A Zone': camera_zones/create-zone.md
  - 'Zone Options': camera_zones/camera-zone-options.md
- 'Local Multiplayer': 
  - 'Overview': multiplayer/multiplayer.md
- 'Modifying The Sphere Mesh':
  - 'Change Size / Color': modify_mesh/size-color.md
  - 'Using Your Own Mesh': modify_mesh/custom-mesh.md
- 'Modifying The Player Object':
  - 'Structure Overview': playersphere_object/structure-overview.md

extra_css: [style.css]